// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package org.apache.mesos.v1.mesos

sealed trait Status extends _root_.com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = Status
  def isDriverNotStarted: Boolean = false
  def isDriverRunning: Boolean = false
  def isDriverAborted: Boolean = false
  def isDriverStopped: Boolean = false
  def companion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[Status] = org.apache.mesos.v1.mesos.Status
}

object Status extends _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[Status] {
  implicit def enumCompanion: _root_.com.trueaccord.scalapb.GeneratedEnumCompanion[Status] = this
  @SerialVersionUID(0L)
  case object DRIVER_NOT_STARTED extends Status {
    val value = 1
    val index = 0
    val name = "DRIVER_NOT_STARTED"
    override def isDriverNotStarted: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DRIVER_RUNNING extends Status {
    val value = 2
    val index = 1
    val name = "DRIVER_RUNNING"
    override def isDriverRunning: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DRIVER_ABORTED extends Status {
    val value = 3
    val index = 2
    val name = "DRIVER_ABORTED"
    override def isDriverAborted: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object DRIVER_STOPPED extends Status {
    val value = 4
    val index = 3
    val name = "DRIVER_STOPPED"
    override def isDriverStopped: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends Status with _root_.com.trueaccord.scalapb.UnrecognizedEnum
  
  lazy val values = scala.collection.Seq(DRIVER_NOT_STARTED, DRIVER_RUNNING, DRIVER_ABORTED, DRIVER_STOPPED)
  def fromValue(value: Int): Status = value match {
    case 1 => DRIVER_NOT_STARTED
    case 2 => DRIVER_RUNNING
    case 3 => DRIVER_ABORTED
    case 4 => DRIVER_STOPPED
    case __other => Unrecognized(__other)
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.EnumDescriptor = MesosProto.javaDescriptor.getEnumTypes.get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.EnumDescriptor = MesosProto.scalaDescriptor.enums(0)
}