// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO2

package org.apache.mesos.v1.quota

object QuotaProto {
  private lazy val ProtoBytes: Array[Byte] =
      com.trueaccord.scalapb.Encoding.fromBase64(scala.collection.Seq(
  """ChptZXNvcy92MS9xdW90YS9xdW90YS5wcm90bxIObWVzb3MudjEucXVvdGEaFG1lc29zL3YxL21lc29zLnByb3RvIm8KCVF1b
  3RhSW5mbxISCgRyb2xlGAEgASgJUgRyb2xlEhwKCXByaW5jaXBhbBgCIAEoCVIJcHJpbmNpcGFsEjAKCWd1YXJhbnRlZRgDIAMoC
  zISLm1lc29zLnYxLlJlc291cmNlUglndWFyYW50ZWUicQoMUXVvdGFSZXF1ZXN0EhsKBWZvcmNlGAEgASgIOgVmYWxzZVIFZm9yY
  2USEgoEcm9sZRgCIAEoCVIEcm9sZRIwCglndWFyYW50ZWUYAyADKAsyEi5tZXNvcy52MS5SZXNvdXJjZVIJZ3VhcmFudGVlIj4KC
  1F1b3RhU3RhdHVzEi8KBWluZm9zGAEgAygLMhkubWVzb3MudjEucXVvdGEuUXVvdGFJbmZvUgVpbmZvc0IjChlvcmcuYXBhY2hlL
  m1lc29zLnYxLnF1b3RhQgZQcm90b3M="""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, Seq(
      org.apache.mesos.v1.mesos.MesosProto.scalaDescriptor
    ))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val proto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(proto, Array(
    org.apache.mesos.v1.mesos.MesosProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}